#!/bin/bash
# 修复群晖 NAS PostgreSQL Docker 访问权限

echo "=== 群晖 PostgreSQL Docker 访问修复脚本 ==="
echo ""
echo "请手动执行以下步骤:"
echo ""
echo "1. 启用群晖 SSH:"
echo "   控制面板 → 终端机和SNMP → 启用SSH服务"
echo ""
echo "2. SSH 登录 NAS (用管理员账号):"
echo "   ssh admin@192.168.88.188"
echo "   或"
echo "   ssh rockts@192.168.88.188"
echo ""
echo "3. 备份并编辑 pg_hba.conf:"
echo "   sudo cp /volume1/pgsql/pg_hba.conf /volume1/pgsql/pg_hba.conf.backup"
echo "   sudo vi /volume1/pgsql/pg_hba.conf"
echo ""
echo "4. 在文件末尾添加以下两行 (允许 Docker 网络访问):"
echo "   # Allow Docker network"
echo "   host    all             all             172.17.0.0/16           md5"
echo "   host    all             all             172.18.0.0/16           md5"
echo ""
echo "5. 保存后重启 PostgreSQL:"
echo "   sudo synopkg restart pgsql"
echo ""
echo "6. 验证 PostgreSQL 正在运行:"
echo "   sudo synopkg status pgsql"
echo "   ps aux | grep postgres"
echo ""
echo "7. 测试 Docker 容器连接:"
echo "   # 在 NAS 上"
echo "   docker exec xiaole-backend psql -U xiaole_user -d xiaole_ai -h 192.168.88.188"
echo ""
echo "=== 完成后重新部署 Docker 容器 ==="
